### ISSUE TITLE
a bug when chown command is called with just the GID, no UID.

### ISSUE THREAD

**Issue by hradec** [Doloops/mcachefs#11]
There's a bug happening when a `chown` is being issued to a folder which sets just the group, without a user:
```
chown :700 '/folder'
```

when this is issued, the journal reports this: 

```
[0] chown (9) : path='/folder', to='' : mode=0, dev=0, uid=4294967295, gid=700, size=0, utimebuf=0,0
```

so it seems when a `chown` without a user is issued, mcachefs "fills up" the missing UID with 0xFFFFFFFF automatically, instead of maintaining the UID the folder already have. 

I'm working on fix it, but I would appreciate any pointers from someone who already knowns the code better than me!

**Comment by Doloops** [comment]
This was fixed in commit 44c0bc7c391e2322d802c2ba24231f9c2085d5e8, PR #13.

Thanks @hradec !
